emx_version: "0.1.0"
emotions: [joy, trust, fear, surprise, sadness, disgust, anger, anticipation]
matrix:  # W[i][j] : j→i
  #      joy trust fear surprise sadness disgust anger anticipation
  - [ 0.2, 0.1, -0.2, 0.0, -0.3, -0.2, -0.3,  0.2 ]  # joy
  - [ 0.1, 0.2, -0.2, 0.0, -0.1, -0.2, -0.2,  0.1 ]  # trust
  - [-0.2,-0.1,  0.3, 0.2,  0.2,  0.3,  0.2, -0.1 ]  # fear
  - [ 0.0, 0.0,  0.2, 0.2, -0.1, -0.1,  0.1,  0.1 ]  # surprise
  - [-0.3,-0.1,  0.2,-0.1,  0.3,  0.2,  0.2, -0.2 ]  # sadness
  - [-0.2,-0.2,  0.3,-0.1,  0.2,  0.3,  0.3, -0.2 ]  # disgust
  - [-0.3,-0.2,  0.2, 0.1,  0.2,  0.3,  0.3, -0.1 ]  # anger
  - [ 0.2, 0.1, -0.1, 0.1, -0.2, -0.2, -0.1,  0.2 ]  # anticipation
params:
  decay: 0.05
  dt: 0.1
  temperature: 1.0
  nonlinearity: tanh
  caps: [1,1,1,1,1,1,1,1]
  inhibitors:
    - {source: anger, target: joy, factor: 0.4}
    - {source: disgust, target: trust, factor: 0.5}
  policy:
    isnt_operator:
      bind_to_nearest_clause: true
      drop_weaker_anchor: true
    zero_equals_one_probe: true
initial_state: [0.2, 0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2]
metadata:
  name: "base-8"
  description: "Reference 8-emotion matrix, inhibitory routes, symbolic probes"
